### ISSUE TITLE
Add documentation through terradocs to the aws-managed-services module

### ISSUE THREAD

**Issue by adrielp** [liatrio/aws-managed-services#15]
# Overview

Make documentation for terraform generated through terra-docs

## AC
* documentation is updated ROFL
* github workflow is added to validate docs have been updated
* makefile is added to run documentation update
* pre-commit is added also

**Comment by adrielp** [comment]
https://terraform-docs.io/

**Comment by shwaddell28** [comment]
https://github.com/liatrio/aws-managed-services/pull/23
